### ISSUE TITLE
Why I can't get_webrtc? Is my network problem?

### ISSUE THREAD

**Issue by xiaodao1990** [pristineio/webrtc-build-scripts#151]
error log!
create a new branch for your work.
[23:06:23] Finished.
----------------------------------------

________ running '/usr/bin/python src/build/landmines.py' in '/home/lll/下载/webrtc-build-scripts-master/android/webrtc/src/chromium'

________ running '/usr/bin/python src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' in '/home/lll/下载/webrtc-build-scripts-master/android/webrtc/src/chromium'

________ running '/usr/bin/python src/build/android/play_services/update.py download' in '/home/lll/下载/webrtc-build-scripts-master/android/webrtc/src/chromium'
Error: Command '/usr/bin/python src/build/android/play_services/update.py download' returned non-zero exit status 1 in /home/lll/下载/webrtc-build-scripts-master/android/webrtc/src/chromium
Traceback (most recent call last):
  File "src/build/android/play_services/update.py", line 512, in <module>
    sys.exit(main(sys.argv[1:]))
  File "src/build/android/play_services/update.py", line 96, in main
    return args.func(args)
  File "src/build/android/play_services/update.py", line 155, in Download
    paths = PlayServicesPaths(args.sdk_root, config.version_xml_path)
  File "src/build/android/play_services/update.py", line 487, in __init__
    self.version_xml = os.path.join(self.lib, version_xml_path)
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)
Error: Command '/usr/bin/python -u src/sync_chromium.py --target-revision d66326c14bb70a1d61d75b096a9a344bc9a53c1a' returned non-zero exit status 2 in /home/lll/下载/webrtc-build-scripts-master/android/webrtc
Hook '/usr/bin/python -u src/sync_chromium.py --target-revision d66326c14bb70a1d61d75b096a9a344bc9a53c1a' took 83193.36 secs
lll@lll-VirtualBox:~/下载/webrtc-build-scripts-master$

**Comment by ArikYa** [comment]
try to run it in a path with only English letters, I think the issue is with the non-ascii characters in your path

**Comment by Ev3rlasting** [comment]
Usually you don't want script to deal with Chinese characters. So change your path to an English one.
