### ISSUE TITLE
Release build for apprtc failed for revision 17231

### ISSUE THREAD

**Issue by hypeapps** [pristineio/webrtc-build-scripts#222]
build_apprtc give me this output:
> Setting up build environment for Android
> Export the base settings of GYP_DEFINES so we can define how we want to build
> User has not specified any gyp defines so we proceed with default
> ARMv7 with Neon Build
> GYP_DEFINES=host_os=linux libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 enable_tracing=1 enable_android_opensl=0 use_sysroot=0 include_tests=0 fastbuild=2 OS=android
> Generate projects using GN
> Done. Made 2783 targets from 171 files in 6641ms
> Build AppRTCMobile in Release (arch: armv7)
> Running ninja
> ninja: Entering directory out_android_arm/Release' [2/3205] ACTION //base:android_runtime...//build/toolchain/android:android_arm) FAILED: gen/android_runtime_jni_headers/base/jni/Runtime_jni.h python ../../base/android/jni_generator/jni_generator.py --depfile gen/base/android_runtime_jni_headers__jni_Runtime.d --jar_file ../../third_party/android_tools/sdk/platforms/android-24/android.jar --input_file java/lang/Runtime.class --optimize_generation=1 --ptr_type=long --output_dir gen/android_runtime_jni_headers/base/jni --includes ../../../../../../base/android/jni_generator/jni_generator_helper.h --native_exports_optional Traceback (most recent call last): File "../../base/android/jni_generator/jni_generator.py", line 1418, in <module> sys.exit(main(sys.argv)) File "../../base/android/jni_generator/jni_generator.py", line 1411, in main GenerateJNIHeader(input_file, output_file, options) File "../../base/android/jni_generator/jni_generator.py", line 1314, in GenerateJNIHeader jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options) File "../../base/android/jni_generator/jni_generator.py", line 663, in CreateFromClass stderr=subprocess.PIPE) File "/usr/lib/python2.7/subprocess.py", line 679, in __init__ errread, errwrite) File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child raise child_exception OSError: [Errno 2] No such file or directory [4/3205] CC obj/third_party/boringssl/boringssl/pem_info.o ninja: build stopped: subcommand failed. Release build for apprtc failed for revision 17231 Setting up build environment for Android Export the base settings of GYP_DEFINES so we can define how we want to build User has not specified any gyp defines so we proceed with default ARMv8 with Neon Build GYP_DEFINES=host_os=linux libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 enable_tracing=1 enable_android_opensl=0 use_sysroot=0 include_tests=0 fastbuild=2 OS=android target_arch=arm64 target_subarch=arm64 Generate projects using GN Done. Made 2777 targets from 171 files in 6529ms Build AppRTCMobile in Release (arch: armv8) Running ninja ninja: Entering directoryout_android_arm64/Release'
> [6/3098] ACTION //base:android_runtime...build/toolchain/android:android_arm64)
> FAILED: gen/android_runtime_jni_headers/base/jni/Runtime_jni.h
> python ../../base/android/jni_generator/jni_generator.py --depfile gen/base/android_runtime_jni_headers__jni_Runtime.d --jar_file ../../third_party/android_tools/sdk/platforms/android-24/android.jar --input_file java/lang/Runtime.class --optimize_generation=1 --ptr_type=long --output_dir gen/android_runtime_jni_headers/base/jni --includes ../../../../../../base/android/jni_generator/jni_generator_helper.h --native_exports_optional
> Traceback (most recent call last):
> File "../../base/android/jni_generator/jni_generator.py", line 1418, in
> sys.exit(main(sys.argv))
> File "../../base/android/jni_generator/jni_generator.py", line 1411, in main
> GenerateJNIHeader(input_file, output_file, options)
> File "../../base/android/jni_generator/jni_generator.py", line 1314, in GenerateJNIHeader
> jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
> File "../../base/android/jni_generator/jni_generator.py", line 663, in CreateFromClass
> stderr=subprocess.PIPE)
> File "/usr/lib/python2.7/subprocess.py", line 679, in init
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory
> [8/3098] CC obj/third_party/boringssl/boringssl/rsa.o
> ninja: build stopped: subcommand failed.
> Release build for apprtc failed for revision 17231
> Setting up build environment for Android
> Export the base settings of GYP_DEFINES so we can define how we want to build
> User has not specified any gyp defines so we proceed with default
> x86 Build
> GYP_DEFINES=host_os=linux libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 enable_tracing=1 enable_android_opensl=0 use_sysroot=0 include_tests=0 fastbuild=2 OS=android target_arch=ia32
> Generate projects using GN
> Done. Made 2805 targets from 172 files in 6940ms
> Build AppRTCMobile in Release (arch: x86)
> Running ninja
> ninja: Entering directory out_android_x86/Release' [4/3358] ACTION //base:android_runtime...//build/toolchain/android:android_x86) FAILED: gen/android_runtime_jni_headers/base/jni/Runtime_jni.h python ../../base/android/jni_generator/jni_generator.py --depfile gen/base/android_runtime_jni_headers__jni_Runtime.d --jar_file ../../third_party/android_tools/sdk/platforms/android-24/android.jar --input_file java/lang/Runtime.class --optimize_generation=1 --ptr_type=long --output_dir gen/android_runtime_jni_headers/base/jni --includes ../../../../../../base/android/jni_generator/jni_generator_helper.h --native_exports_optional Traceback (most recent call last): File "../../base/android/jni_generator/jni_generator.py", line 1418, in <module> sys.exit(main(sys.argv)) File "../../base/android/jni_generator/jni_generator.py", line 1411, in main GenerateJNIHeader(input_file, output_file, options) File "../../base/android/jni_generator/jni_generator.py", line 1314, in GenerateJNIHeader jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options) File "../../base/android/jni_generator/jni_generator.py", line 663, in CreateFromClass stderr=subprocess.PIPE) File "/usr/lib/python2.7/subprocess.py", line 679, in __init__ errread, errwrite) File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child raise child_exception OSError: [Errno 2] No such file or directory [6/3358] CC obj/third_party/boringssl/boringssl/ctr.o ninja: build stopped: subcommand failed. Release build for apprtc failed for revision 17231 Setting up build environment for Android Export the base settings of GYP_DEFINES so we can define how we want to build User has not specified any gyp defines so we proceed with default x86_64 Build GYP_DEFINES=host_os=linux libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 enable_tracing=1 enable_android_opensl=0 use_sysroot=0 include_tests=0 fastbuild=2 OS=android target_arch=x64 Generate projects using GN Done. Made 2805 targets from 172 files in 7060ms Build AppRTCMobile in Release (arch: x86_64) Running ninja ninja: Entering directoryout_android_x64/Release'
> [4/3352] ACTION //base:android_runtime...//build/toolchain/android:android_x64)
> FAILED: gen/android_runtime_jni_headers/base/jni/Runtime_jni.h
> python ../../base/android/jni_generator/jni_generator.py --depfile gen/base/android_runtime_jni_headers__jni_Runtime.d --jar_file ../../third_party/android_tools/sdk/platforms/android-24/android.jar --input_file java/lang/Runtime.class --optimize_generation=1 --ptr_type=long --output_dir gen/android_runtime_jni_headers/base/jni --includes ../../../../../../base/android/jni_generator/jni_generator_helper.h --native_exports_optional
> Traceback (most recent call last):
> File "../../base/android/jni_generator/jni_generator.py", line 1418, in
> sys.exit(main(sys.argv))
> File "../../base/android/jni_generator/jni_generator.py", line 1411, in main
> GenerateJNIHeader(input_file, output_file, options)
> File "../../base/android/jni_generator/jni_generator.py", line 1314, in GenerateJNIHeader
> jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
> File "../../base/android/jni_generator/jni_generator.py", line 663, in CreateFromClass
> stderr=subprocess.PIPE)
> File "/usr/lib/python2.7/subprocess.py", line 679, in init
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory
> [6/3352] CC obj/third_party/boringssl/boringssl/obj.o
> ninja: build stopped: subcommand failed.
> Release build for apprtc failed for revision 17231

Am I doing something wrong?

**Comment by hypeapps** [comment]
I ran 
> install-build-deps-android.sh 

located in src/build/ and build_apprtc worked
