### ISSUE TITLE
building webrtc for android fails: loading build.ninja No such file or directory

### ISSUE THREAD

**Issue by eeethenQ** [pristineio/webrtc-build-scripts#246]
I want to compile an android version but encounter some problems when executing `build_apprtc`.

Here is the outcome:
```
Setting up build environment for Android
Export the base settings of GYP_DEFINES so we can define how we want to build
User has not specified any gyp defines so we proceed with default
ARMv7 with Neon Build
GYP_DEFINES=host_os=linux libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 enable_tracing=1 enable_android_opensl=0 use_sysroot=0 include_tests=0 fastbuild=2 OS=android
Generate projects using GN
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /root/webrtc-build-scripts/android/webrtc/src/out_android_arm/Release/
Command: python /root/webrtc-build-scripts/android/webrtc/src/build/config/linux/pkg-config.py -s /root/webrtc-build-scripts/android/webrtc/src/build/linux/debian_sid_amd64-sysroot -a x64 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/root/webrtc-build-scripts/android/webrtc/src/build/config/linux/pkg-config.py", line 246, in <module>
    sys.exit(main())
  File "/root/webrtc-build-scripts/android/webrtc/src/build/config/linux/pkg-config.py", line 141, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/root/webrtc-build-scripts/android/webrtc/src/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/BUILD.gn:89:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //build/config/compiler/BUILD.gn:225:18: which caused the file to be included.
    configs += [ "//build/config/linux:compiler" ]
                 ^------------------------------
Build AppRTCMobile in Release (arch: armv7)
Running ninja
ninja: Entering directory `out_android_arm/Release'
ninja: error: loading 'build.ninja': No such file or directory
Release build for apprtc failed for revision 26358
```
I have tried to `sudo apt install ninja ninja-build` but it doesn't work.

**Comment by glumes** [comment]
i have the same problem

**Comment by ionphractal** [comment]
Could be missing glib dev? Try `apt-get install libglib2.0-dev` and see if that solves it.

**Comment by aagmangour** [comment]
Make sure all dependencies are installed. libglib2.0-dev libgtk2.0-dev libxtst-dev libxss-dev libpci-dev libdbus-1-dev libgconf2-dev
