### ISSUE TITLE
Error build in XCode 6.1.1

### ISSUE THREAD

**Issue by Droppix** [pristineio/webrtc-build-scripts#35]
Hi,

Compile with XCode 6.1.1, an idea?

________ running '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/Users/robert/Dev/Web/webrtc-build-scripts-master/ios/webrtc'
Updating projects from gyp files...
Traceback (most recent call last):
  File "src/webrtc/build/gyp_webrtc", line 100, in <module>
    gyp_rc = gyp.main(args)
  File "/Users/robert/Dev/Web/webrtc-build-scripts-master/ios/webrtc/src/chromium/src/tools/gyp/pylib/gyp/**init**.py", line 525, in main
    return gyp_main(args)
  File "/Users/robert/Dev/Web/webrtc-build-scripts-master/ios/webrtc/src/chromium/src/tools/gyp/pylib/gyp/**init**.py", line 510, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/robert/Dev/Web/webrtc-build-scripts-master/ios/webrtc/src/chromium/src/tools/gyp/pylib/gyp/generator/ninja.py", line 2376, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AssertionError: Multiple codesigning fingerprints for identity: iPhone Developer
Error: Command /usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /Users/robert/Dev/Web/webrtc-build-scripts-master/ios/webrtc
ninja: Entering directory `out_ios_armeabi_v7a/Debug-iphoneos/'
ninja: error: build.ninja:98: unexpected EOF
  description = MERGE INFOPL
                            ^ near here
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/robert/Dev/Web/webrtc-build-scripts-master/ios/webrtc/src/out_ios_armeabi_v7a/Debug-iphoneos/*.a (No such file or directory)
Running depot tools as root is sad

**Comment by temahussain** [comment]
Try XCode 6.1

**Comment by thebehera** [comment]
unfortunately there was a typo when in one of the built products so pull to the latest, but 

AssertionError: Multiple codesigning fingerprints for identity: iPhone Developer
can be fixed by only using one fingerprint in the login keychain

**Comment by ArikYa** [comment]
@RobertNNms, can you pull the latest and retry?
