### ISSUE TITLE
get_webrtc ends/halts with an error (Mac OSX Yosemite and Ubuntu 14.04)

### ISSUE THREAD

**Issue by rishabhp** [pristineio/webrtc-build-scripts#55]
I'm running the build scripts on Mac Yosemite (with vagrant) and this is how the `get_webrtc` command crashed after 2hours (with errors), anyone know what can be done to fix this:

```bash
[2:00:21] Still working on:
[2:00:21]   src/third_party/android_tools
[2:00:22] Still working on:
[2:00:22]   src/third_party/android_tools

________ running '/usr/bin/python src/build/landmines.py' in '/vagrant/webrtc/src/chromium'

________ running '/usr/bin/python src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync' in '/vagrant/webrtc/src/chromium'

________ running '/usr/bin/python src/build/download_sdk_extras.py' in '/vagrant/webrtc/src/chromium'

________ running '/usr/bin/python src/chrome/installer/linux/sysroot_scripts/install-debian.wheezy.sysroot.py --linux-only' in '/vagrant/webrtc/src/chromium'

________ running '/usr/bin/python src/build/vs_toolchain.py update' in '/vagrant/webrtc/src/chromium'

________ running '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' in '/vagrant/webrtc/src/chromium'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.9M  100 23.9M    0     0  1450k      0  0:00:16  0:00:16 --:--:-- 3112k
Trying to download prebuilt clang
clang 223108 unpacked
Hook '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' took 18.60 secs

________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/vagrant/webrtc/src/chromium'

________ running '/usr/bin/python src/build/util/lastchange.py -s src/third_party/WebKit -o src/build/util/LASTCHANGE.blink' in '/vagrant/webrtc/src/chromium'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s src/buildtools/win/gn.exe.sha1' in '/vagrant/webrtc/src/chromium'

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s src/buildtools/mac/gn.sha1' in '/vagrant/webrtc/src/chromium'

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s src/buildtools/linux32/gn.sha1' in '/vagrant/webrtc/src/chromium'
0> Downloading src/buildtools/linux32/gn...
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-gn -s src/buildtools/linux32/gn.sha1' took 55.64 secs

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' in '/vagrant/webrtc/src/chromium'
0> Downloading src/buildtools/linux64/gn...
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' took 45.03 secs

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s src/buildtools/win/clang-format.exe.sha1' in '/vagrant/webrtc/src/chromium'

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s src/buildtools/mac/clang-format.sha1' in '/vagrant/webrtc/src/chromium'

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/vagrant/webrtc/src/chromium'
0> Downloading src/buildtools/linux64/clang-format...
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' took 47.21 secs

________ running '/usr/bin/python src/third_party/binutils/download.py' in '/vagrant/webrtc/src/chromium'
Error: Command /usr/bin/python src/third_party/binutils/download.py returned non-zero exit status 1 in /vagrant/webrtc/src/chromium
0> Downloading /vagrant/webrtc/src/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2...
tar: ./bin/ld.gold: Cannot hard link to `./bin/ld': Operation not permitted
tar: Exiting with failure status due to previous errors
Downloading /vagrant/webrtc/src/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /vagrant/webrtc/src/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2
Traceback (most recent call last):
  File "src/third_party/binutils/download.py", line 118, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/binutils/download.py", line 106, in main
    return FetchAndExtract(arch)
  File "src/third_party/binutils/download.py", line 91, in FetchAndExtract
    subprocess.check_call(['tar', 'axf', tarball], cwd=outdir)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', 'axf', '/vagrant/webrtc/src/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2']' returned non-zero exit status 2
Hook '/usr/bin/python src/third_party/binutils/download.py' took 53.78 secs
Error: Command /usr/bin/python -u src/sync_chromium.py --target-revision 4664fe0d123f948bafa7b942717fc5847e61971c returned non-zero exit status 2 in /vagrant/webrtc
Hook '/usr/bin/python -u src/sync_chromium.py --target-revision 4664fe0d123f948bafa7b942717fc5847e61971c' took 7448.52 secs
```

**Comment by imadeit** [comment]
I had the same problem before, when I asked the WebRTC member, they asked me to ask vagrant, how...

**Comment by rishabhp** [comment]
@imadeit "they asked me to ask vagrant, how..." ? Sorry but I didn't get you.

**Comment by rishabhp** [comment]
Anyway, gonna try it on Ubuntu on VirtualBox (on Mac Yosemite without vagrant) and update you.

**Comment by rishabhp** [comment]
Tried on Ubuntu 14.04 (VirtualBox on Mac Yosemite). After like 4 hours it crashed with this dump:

```bash
5> Downloading src/resources/audio_coding/F05.BIT20...
1> Downloading src/resources/audio_coding/F00.OUT20...
6> Downloading src/resources/audio_coding/F01.OUT30...
3> Downloading src/resources/audio_coding/neteq_universal_ref.pcm...
8> Downloading src/resources/audio_coding/teststereo32kHz.pcm...
0> Downloading src/resources/audio_coding/F06.INP...
Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --bucket chromium-webrtc-resources src/resources' took 2390.32 secs

________ running '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/home/rishabh/webrtc-build-scripts/android/webrtc'
Updating projects from gyp files...
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gthread-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gthread-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gthread-2.0' found
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
gyp: Call to 'pkg-config --libs-only-l glib-2.0 gobject-2.0 gthread-2.0 gtk+-2.0' returned exit status 1.
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gthread-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gthread-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gthread-2.0' found
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
gyp: Call to 'pkg-config --libs-only-l gobject-2.0 gthread-2.0 gtk+-2.0' returned exit status 1.
Error: Command /usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /home/rishabh/webrtc-build-scripts/android/webrtc
```

Hope someone will be able to help! What should I do and make sure that on a re-run I don't have to go through those 4 hours again, instead resume from where it halted ?

**Comment by imadeit** [comment]
@rishabhp 
> "they asked me to ask vagrant, how..." ? I didn't get you.
I just wanted to say how could they be so irresponsible...

I see your log, I suggest you use Ubuntu12.04 AMD 64 bit, it should success, you have to install the dependent libraries however.

**Comment by rishabhp** [comment]
@imadeit yup, I was able to build with the help of https://github.com/pristineio/webrtc-build-scripts/issues/21

Just had to execute `./android/webrtc/src/build/install-build-deps-android.sh` and then `build_apprtc`. It succeeded with the following dump:

```bash
/home/rishabh/webrtc-build-scripts/android/webrtc/libjingle_peerconnection_builds/Release/jniLibs/x86_64 directory not found, creating...
directory created at /home/rishabh/webrtc-build-scripts/android/webrtc/libjingle_peerconnection_builds/Release/jniLibs/x86_64
  adding: jniLibs/ (stored 0%)
  adding: jniLibs/x86_64/ (stored 0%)
  adding: jniLibs/x86_64/libjingle_peerconnection_so.so (deflated 58%)
  adding: jniLibs/x86/ (stored 0%)
  adding: jniLibs/x86/libjingle_peerconnection_so.so (deflated 58%)
  adding: jniLibs/armeabi_v7a/ (stored 0%)
  adding: jniLibs/armeabi_v7a/libjingle_peerconnection_so.so (deflated 43%)
  adding: res/ (stored 0%)
  adding: libs/ (stored 0%)
  adding: libs/libjingle_peerconnection.jar (deflated 10%)
Release build for apprtc complete for revision 8148
```

:)

**Comment by rajeshevv** [comment]
Hi @rishabhp .. hope you are doing fine.
I am currently working on webrtc implementation in ios.
Facing this error everytime i do fetch webrtc_ios
 raise CalledProcessError(retcode, cmd).

Can you just help me out to fix this problem?

It will be helpfull for me.
